name: radia_mpi_env
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli=1.2.0=h17ff524_0
  - brotli-bin=1.2.0=h6910e44_0
  - brotli-python=1.0.9=py38hd3f51b4_8
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38h4cb3324_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.1.1=py38hb1fd069_1
  - cycler=0.12.1=pyhd8ed1ab_0
  - fonttools=4.53.1=py38h4cb3324_0
  - freetype=2.14.1=h57928b3_0
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - glib=2.86.2=h19e2e61_1
  - glib-tools=2.86.2=he647baa_1
  - gst-plugins-base=1.21.3=h001b923_1
  - gstreamer=1.21.3=h6b5321d_1
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=70.1=h0e60522_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=hcfcfb64_3
  - kiwisolver=1.4.5=py38hb1fd069_1
  - krb5=1.20.1=h6609f42_0
  - lcms2=2.15=ha5c8aab_0
  - lerc=4.0.0=h6470a55_1
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libblas=3.11.0=1_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libcblas=3.11.0=1_h2a3cdd5_mkl
  - libclang=15.0.7=default_h3a3e6c3_5
  - libclang13=15.0.7=default_hf64faad_5
  - libdeflate=1.17=hcfcfb64_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libglib=2.86.2=h0c9aed9_1
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - liblapack=3.11.0=1_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libogg=1.3.5=h2466b09_1
  - libpng=1.6.50=h7351971_1
  - libsqlite=3.51.0=hf5d6505_0
  - libtiff=4.5.0=hf8721a0_2
  - libvorbis=1.3.7=h5112557_2
  - libwebp-base=1.6.0=h4d5522a_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.6=h4fa8253_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.7.3=py38haa244fe_0
  - matplotlib-base=3.7.3=py38h2724991_0
  - mkl=2025.3.0=hac47afa_454
  - mpi=1.0=msmpi
  - mpi4py=4.0.0=py38h85849be_1
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msmpi=10.1.1=h3502643_7
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - numpy=1.24.4=py38h1d91fd2_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=1.1.1w=hcfcfb64_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.47=hd2b5f0e_0
  - pillow=9.4.0=py38h087119c_1
  - pip=24.3.1=pyh8b19718_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - pooch=1.8.2=pyhd8ed1ab_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pyaml=24.9.0=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyqt=5.15.7=py38hd6c051e_3
  - pyqt5-sip=12.11.0=py38hd3f51b4_3
  - pysocks=1.7.1=pyh0701188_6
  - python=3.8.0=hc9e8b01_5
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pyyaml=6.0.2=py38h4cb3324_0
  - qt-main=5.15.6=h068e40c_6
  - requests=2.32.3=pyhd8ed1ab_0
  - scikit-learn=1.3.2=py38h4f736e5_2
  - scikit-optimize=0.10.2=pyhd8ed1ab_0
  - scipy=1.10.1=py38h1aea9ed_3
  - setuptools=75.3.0=pyhd8ed1ab_0
  - sip=6.7.12=py38hd3f51b4_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.51.0=hdb435a2_0
  - sympy=1.13.3=pyh04b8f61_4
  - tbb=2022.3.0=hd094cb3_1
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=h2c6b04d_3
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.2=pyhd8ed1ab_0
  - tornado=6.4.1=py38h4cb3324_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=15.1.0=py38h91455d4_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wheel=0.45.1=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_7
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - yaml=0.2.5=h6a83c73_3
  - zipp=3.21.0=pyhd8ed1ab_0
  - zstandard=0.19.0=py38h91455d4_0
  - zstd=1.5.7=hbeecb71_2
